name = "workers-airtable-form"
type = "javascript"

account_id = "1038c3baca04a332bdbe1736359e7525"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "appeSWNykwi3SMV4O"
AIRTABLE_TABLE_NAME = "Form Submissions"
FORM_URL = "workers-airtable-form-bzw.pages.dev"
