name = "workers-airtable-form"
type = "javascript"

account_id = "1038c3baca04a332bdbe1736359e7525"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "apppdHQznEXZR3CXY"
AIRTABLE_TABLE_NAME = "Responses"
FORM_URL = "workers-airtable-form-bzw.pages.dev"
